// @generated by tools/e2e/ime_key_matrix/gen_key_effect_table.py — 手で編集しない（ADR-191 決定3・4）。
// 生成元: tools/e2e/ime_key_matrix/grid-tables/{atok,msime,msime-native}.json（GitHub CI の --grid --grid-setup=keys 学習結果=第3版。全状態をキーだけで作る）。
// 全試行で結果が一致したセルだけを含む（非決定セル・未観測セル・履歴依存の追加ブロックは「予測なし」）。
// 閉(OFF)のセルは変換モードを問わない（conv=None）。押下後convが不明なセルは after_conv=None（追跡を捨てる）。
// MSIME は「GJI の MS-IME プリセット」の表（Microsoft IME 本体ではない）。MSIME_NATIVE が Microsoft IME 本体の表。
// MSIME は各セル2試行で非決定を検出しきれないため、ATOK で割れた変換中のEsc・入力中のBS/Escは変換モードを問わず除外した。
// MSIME_NATIVE は206/227セルが1試行のみ（独立walkの採点で確認、非決定6セルは除外済み）。
// 測定環境: 不明(grid-tables/measurement-env.json が無いか読めない、ADR-196決定1d参照)

use super::key_effect_predictor::{cell, Cell, Conv, Disp, Stage, TableKey};

#[rustfmt::skip]
pub(super) const ATOK: &[Cell] = &[
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Esc, true, Some(Conv::C10), Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Bs, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Enter, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Esc, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOn, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Katakana, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Space, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Katakana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Esc, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];
#[rustfmt::skip]
pub(super) const MSIME: &[Cell] = &[
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Bs, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Enter, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Esc, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Henkan, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::ImeOn, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Muhenkan, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::None, TableKey::Space, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Enter, true, Some(Conv::C10), Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Henkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C10), Stage::Typing, TableKey::Space, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, true, Some(Conv::C10), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Henkan, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Bs, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Eisu, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Enter, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Esc, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Henkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOn, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Space, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Eisu, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::HankakuZenkaku, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOff, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Kanji, false, None, Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];
#[rustfmt::skip]
pub(super) const MSIME_NATIVE: &[Cell] = &[
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C19), Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Bs, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Enter, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Esc, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C19), Stage::None, TableKey::Space, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Enter, true, Some(Conv::C19), Disp::Committed),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Henkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C19), Stage::Typing, TableKey::Space, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvHenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Esc, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvMuhenkan, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Bs, true, Some(Conv::C1B), Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::ConvSpace, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Bs, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Eisu, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Enter, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Esc, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::HankakuZenkaku, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Hiragana, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::ImeOn, true, Some(Conv::C19), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Kanji, false, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Katakana, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Muhenkan, true, None, Disp::None),
    cell(true, Some(Conv::C1B), Stage::None, TableKey::Space, true, Some(Conv::C1B), Disp::None),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Eisu, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Enter, true, Some(Conv::C1B), Disp::Committed),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::HankakuZenkaku, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Henkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Hiragana, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOff, true, Some(Conv::C10), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::ImeOn, true, Some(Conv::C19), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Kanji, false, None, Disp::Discarded),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Katakana, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Muhenkan, true, Some(Conv::C1B), Disp::Kept),
    cell(true, Some(Conv::C1B), Stage::Typing, TableKey::Space, true, Some(Conv::C1B), Disp::Kept),
    cell(false, None, Stage::None, TableKey::Bs, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Eisu, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Enter, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Esc, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::HankakuZenkaku, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Henkan, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Hiragana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOff, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::ImeOn, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Kanji, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Katakana, true, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Muhenkan, false, None, Disp::None),
    cell(false, None, Stage::None, TableKey::Space, false, None, Disp::None),
];

// --- ADR-192 classification logic (the generator preserves this suffix) ---

/// 状態依存性を判定できない理由（ADR-192決定1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CannotPredictReason {
    /// キーマップの解釈自体が不確か。
    AmbiguousKeymap,
    /// ユーザー固有の上書きが対象キーの意味を変えている。
    UserOverride,
    /// awase側の実測データが不足している。
    InsufficientData,
}

/// 状態依存性が見つかった軸。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StateDependentAxis {
    /// IMEの開閉結果が入力前の状態だけでは決まらない。
    Open,
    /// 未確定文字列の破棄・確定が入力状態によって変わる。
    Composition,
    /// 開閉と未確定文字列の両方。
    OpenAndComposition,
}

/// 対象IMEモードキーの状態依存性（ADR-192決定1）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Classification {
    StateIndependent,
    StateDependent(StateDependentAxis),
    CannotPredict(CannotPredictReason),
}

/// 実測セルを直接横断してIMEモードキーの状態依存性を分類する。
///
/// 対象外のVKは`None`。`KeyEffectKeymap::predict`は実行時向け補正を含むため使わない。
///
/// `learned`は実行時に採用されている学習表のセル（`RuntimeTableCache`、ADR-196/ADR192-T5）。
/// 対象キーのセルを持つときは、同梱表・キーマップ由来のガード（overlay/カスタム表）より先に
/// それで判定する（予測器`predict_with_override`と同じ優先順位。予測器が「冪等」と見ているキーを
/// この警告が「状態依存」と表示する食い違いを防ぐ）。対象キーのセルが無ければ従来どおり。
#[must_use]
pub fn classify_state_dependent_mode_key(
    keymap: Option<&super::key_effect_predictor::KeyEffectKeymap>,
    vk: u16,
    learned: Option<&[Cell]>,
) -> Option<Classification> {
    use super::key_effect_predictor::{custom_table_overrides, KeymapPreset, TableKey};

    let key = match vk {
        0x1C => TableKey::Henkan,
        0x1D => TableKey::Muhenkan,
        0xF3 | 0xF4 => TableKey::HankakuZenkaku,
        0x19 => TableKey::Kanji,
        0x16 => TableKey::ImeOn,
        0x1A => TableKey::ImeOff,
        _ => return None,
    };
    let Some(keymap) = keymap else {
        return Some(Classification::CannotPredict(
            CannotPredictReason::AmbiguousKeymap,
        ));
    };
    if let Some(learned) = learned {
        if learned.iter().any(|cell| cell.key == key) {
            return Some(classify_cells(learned, key, vk));
        }
    }
    if matches!(
        keymap.preset,
        KeymapPreset::MsImeNative | KeymapPreset::Custom
    ) {
        // MsImeNativeと同じ理由: 基準となる同梱表が無い(Customは`session_keymap`が
        // ATOK/MSIME以外、ADR-195段階4 B3対応で`from_config`が`None`ではなく
        // `Custom`プリセットを返すようになった)。
        return Some(Classification::CannotPredict(
            CannotPredictReason::InsufficientData,
        ));
    }
    if keymap.has_overlay() && matches!(key, TableKey::Henkan | TableKey::Muhenkan) {
        return Some(Classification::CannotPredict(
            CannotPredictReason::AmbiguousKeymap,
        ));
    }
    if let Some(custom) = keymap.custom_table.as_deref() {
        // ATOKプリセットでは古いcustom_keymap_tableを信頼できない（ADR-186決定(c)）。
        if keymap.preset == KeymapPreset::Atok {
            return Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap,
            ));
        }
        if custom_table_overrides(custom, vk) {
            return Some(Classification::CannotPredict(
                CannotPredictReason::UserOverride,
            ));
        }
    }

    let cells = match keymap.preset {
        KeymapPreset::Atok => ATOK,
        KeymapPreset::MsIme => MSIME,
        KeymapPreset::MsImeNative | KeymapPreset::Custom => unreachable!("handled above"),
    };
    Some(classify_cells(cells, key, vk))
}

fn classify_cells(cells: &[Cell], key: TableKey, vk: u16) -> Classification {
    let matching: Vec<_> = cells.iter().filter(|cell| cell.key == key).collect();
    if matching.is_empty() {
        return Classification::CannotPredict(CannotPredictReason::InsufficientData);
    }

    let set_on = matching.iter().all(|cell| cell.after_open);
    let set_off = matching.iter().all(|cell| !cell.after_open);
    let toggle = matching.iter().all(|cell| cell.after_open != cell.open);
    let identity = matching.iter().all(|cell| cell.after_open == cell.open);
    let open_dependent = !(set_on || set_off || toggle || identity);

    let composition_dependent = !identity
        && crate::vk::is_physical_ime_mode_key(awase::types::VkCode(vk))
        && [Disp::Discarded, Disp::Committed]
            .into_iter()
            .any(|hazard| {
                let hazardous = matching.iter().filter(|cell| cell.disp == hazard).count();
                hazardous > 0 && hazardous < matching.len()
            });

    match (open_dependent, composition_dependent) {
        (false, false) => Classification::StateIndependent,
        (true, false) => Classification::StateDependent(StateDependentAxis::Open),
        (false, true) => Classification::StateDependent(StateDependentAxis::Composition),
        (true, true) => Classification::StateDependent(StateDependentAxis::OpenAndComposition),
    }
}

/// 学習表がトグルと矛盾すると示した種類（ADR-199 決定6-2）。根拠にするのは開閉の反転そのものを測る
/// `Stage::None`（入力中でない）のセル2種だけ。入力中・変換中のセルは根拠にしない
/// （MS-IME 本体は入力中に開→開の正規挙動があり、同梱表の MSIME_NATIVE は1試行のセルが多い）。
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToggleContradiction {
    /// 閉状態（DirectInput）で押して閉のまま（`after_open=false`）。
    ClosedStaysClosed,
    /// 開状態の未入力で押して開のまま（`after_open=true`）。
    IdleOpenStaysOpen,
}

impl ToggleContradiction {
    /// 不具合報告・ログ用の固定語彙。
    #[must_use]
    pub const fn label(self) -> &'static str {
        match self {
            Self::ClosedStaysClosed => "closed_stays_closed",
            Self::IdleOpenStaysOpen => "idle_open_stays_open",
        }
    }
}

/// 学習表による狭めの対象キー（ADR-199 決定6-2。F13〜F24 は表にセルが無いので対象外）。
pub const NARROWABLE_KEYS: [TableKey; 3] = [
    TableKey::HankakuZenkaku,
    TableKey::Muhenkan,
    TableKey::Henkan,
];

/// ADR-199 決定6-2（PR #308 の半角/全角判定を包含）: 採用中の学習表に、`key` を**開閉トグルとする
/// 割り当てと矛盾するセル**が1つでもあるか。あれば呼び出し側はそのキーを受動にする（能動→受動の
/// 方向だけ。学習表から能動側へは広げない）。
///
/// - 見るのは`Stage::None`のセルだけ（[`ToggleContradiction`]）。閉と開の両方にあれば閉を先に返す。
/// - セルが欠けているだけでは矛盾としない（`None`）。行が無いキー・空の表も`None`。
///
/// `classify_cells`（全セルを見て警告に使う）とは目的が違い、同じ基準ではない。
#[must_use]
pub fn toggle_contradiction(cells: &[Cell], key: TableKey) -> Option<ToggleContradiction> {
    use super::key_effect_predictor::Stage;
    let mut idle = cells
        .iter()
        .filter(|c| c.key() == key && c.stage() == Stage::None);
    let mut found = None;
    for c in idle.by_ref() {
        match (c.open(), c.after_open()) {
            (false, false) => return Some(ToggleContradiction::ClosedStaysClosed),
            (true, true) => found = Some(ToggleContradiction::IdleOpenStaysOpen),
            _ => {}
        }
    }
    found
}

#[cfg(test)]
mod classification_tests {
    use super::*;
    use crate::state::key_effect_predictor::KeyEffectKeymap;

    /// ADR-199 決定6-2: `Stage::None` の閉セル1つ+開セル（C19/C10）を組み立てる。
    /// `(閉→after, C19→after, C10→after)`。
    fn hz_cells(closed_after: bool, c19_after: bool, c10_after: bool) -> Vec<Cell> {
        use super::super::key_effect_predictor::{cell, Conv, Stage};
        let k = TableKey::HankakuZenkaku;
        vec![
            cell(false, None, Stage::None, k, closed_after, None, Disp::None),
            cell(
                true,
                Some(Conv::C19),
                Stage::None,
                k,
                c19_after,
                Some(Conv::C19),
                Disp::None,
            ),
            cell(
                true,
                Some(Conv::C10),
                Stage::None,
                k,
                c10_after,
                Some(Conv::C10),
                Disp::None,
            ),
        ]
    }

    const HZ: TableKey = TableKey::HankakuZenkaku;

    #[test]
    fn pure_toggle_has_no_contradiction() {
        assert_eq!(
            toggle_contradiction(&hz_cells(true, false, false), HZ),
            None
        );
    }

    /// IMEOn/ひらがな割当: 閉→開、開→開。開セルの開→開が矛盾。
    #[test]
    fn open_stays_open_contradicts() {
        assert_eq!(
            toggle_contradiction(&hz_cells(true, true, true), HZ),
            Some(ToggleContradiction::IdleOpenStaysOpen)
        );
    }

    /// 決定6-2: 閉→閉（IMEOff割当）も矛盾（PR #308 は見送っていたが、ADR-199 で対象に含めた）。
    #[test]
    fn closed_stays_closed_contradicts() {
        assert_eq!(
            toggle_contradiction(&hz_cells(false, false, false), HZ),
            Some(ToggleContradiction::ClosedStaysClosed)
        );
        // 閉と開の両方に矛盾があれば閉を先に返す。
        assert_eq!(
            toggle_contradiction(&hz_cells(false, true, true), HZ),
            Some(ToggleContradiction::ClosedStaysClosed)
        );
    }

    /// 決定6-2: 矛盾セルが**1つでも**あれば狭める（開セル1つだけ開→開でも）。
    #[test]
    fn single_contradicting_cell_is_enough() {
        assert_eq!(
            toggle_contradiction(&hz_cells(true, true, false), HZ),
            Some(ToggleContradiction::IdleOpenStaysOpen)
        );
    }

    /// セルが欠けているだけでは狭めない。行が無い・空の表・別キーの行だけも同じ。
    #[test]
    fn missing_cells_or_rows_do_not_contradict() {
        use super::super::key_effect_predictor::{cell, Stage};
        assert_eq!(toggle_contradiction(&[], HZ), None);
        let other = [cell(
            false,
            None,
            Stage::None,
            TableKey::Henkan,
            false,
            None,
            Disp::None,
        )];
        assert_eq!(toggle_contradiction(&other, HZ), None);
        let mut no_closed = hz_cells(true, false, false);
        no_closed.remove(0);
        assert_eq!(toggle_contradiction(&no_closed, HZ), None);
        let mut no_c10 = hz_cells(true, false, false);
        no_c10.pop();
        assert_eq!(toggle_contradiction(&no_c10, HZ), None);
    }

    /// 入力中（Typing）・変換中のセルは、開→開でも根拠にしない（MS-IME 本体の正規挙動・1試行ノイズ）。
    #[test]
    fn non_idle_stage_cells_are_ignored() {
        use super::super::key_effect_predictor::{cell, Conv, Stage};
        for stage in [Stage::Typing, Stage::ConvSpace, Stage::ConvHenkan] {
            let mut cells = hz_cells(true, false, false);
            cells.push(cell(
                true,
                Some(Conv::C19),
                stage,
                HZ,
                true,
                Some(Conv::C10),
                Disp::Kept,
            ));
            cells.push(cell(false, None, stage, HZ, false, None, Disp::Kept));
            assert_eq!(toggle_contradiction(&cells, HZ), None, "{stage:?}");
        }
    }

    /// 同梱表の半角/全角は、GJI の2プリセットも MS-IME 本体も純トグル（誤検出の回帰）。
    /// 同梱表と実機の食い違いをここで拾えるよう、3表すべてで固定する。
    #[test]
    fn bundled_tables_hankaku_zenkaku_is_pure_toggle() {
        for cells in [ATOK, MSIME, MSIME_NATIVE] {
            assert_eq!(toggle_contradiction(cells, HZ), None);
        }
    }

    /// 無変換/変換もキー単位で独立に判定する（他キーの矛盾に引きずられない）。
    #[test]
    fn contradiction_is_per_key() {
        use super::super::key_effect_predictor::{cell, Stage};
        let cells = [cell(
            false,
            None,
            Stage::None,
            TableKey::Muhenkan,
            false,
            None,
            Disp::None,
        )];
        assert_eq!(
            toggle_contradiction(&cells, TableKey::Muhenkan),
            Some(ToggleContradiction::ClosedStaysClosed)
        );
        assert_eq!(toggle_contradiction(&cells, TableKey::Henkan), None);
        assert_eq!(toggle_contradiction(&cells, HZ), None);
    }

    fn classify(preset: i64, vk: u16) -> Option<Classification> {
        let keymap = KeyEffectKeymap::from_config(Some(preset), None, &[]).unwrap();
        classify_state_dependent_mode_key(Some(&keymap), vk, None)
    }

    #[test]
    fn adr192_open_axis_verification_table() {
        for vk in [0x16, 0x1A, 0x19, 0xF3, 0xF4] {
            assert_ne!(
                classify(1, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
            assert_ne!(
                classify(2, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
        }
        for vk in [0x1C, 0x1D] {
            assert_eq!(
                classify(1, vk),
                Some(Classification::StateDependent(StateDependentAxis::Open))
            );
            assert_eq!(classify(2, vk), Some(Classification::StateIndependent));
        }
    }

    #[test]
    fn adr192_composition_axis_verification_table() {
        for preset in [1, 2] {
            for vk in [0x19, 0xF3, 0xF4] {
                assert_eq!(
                    classify(preset, vk),
                    Some(Classification::StateDependent(
                        StateDependentAxis::Composition
                    ))
                );
            }
            for vk in [0x16, 0x1A] {
                assert_eq!(classify(preset, vk), Some(Classification::StateIndependent));
            }
        }
    }

    #[test]
    fn adr192_non_target_keys_are_not_classified() {
        for vk in [0x08, 0x0D, 0x1B, 0x20, 0xF0, 0xF1, 0xF2] {
            assert_eq!(classify(1, vk), None);
        }
    }

    #[test]
    fn adr192_cannot_predict_reasons_are_distinct() {
        assert_eq!(
            classify_state_dependent_mode_key(None, 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
        let overlay = KeyEffectKeymap::from_config(Some(2), None, &[1]).unwrap();
        assert_eq!(
            classify_state_dependent_mode_key(Some(&overlay), 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
        let custom = KeyEffectKeymap::from_config(
            Some(2),
            Some("DirectInput\tHenkan\tIMEOn".to_owned()),
            &[],
        )
        .unwrap();
        assert_eq!(
            classify_state_dependent_mode_key(Some(&custom), 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::UserOverride
            ))
        );
        let native = KeyEffectKeymap::for_msime_native(false, None, None, None);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&native), 0x1C, None),
            Some(Classification::CannotPredict(
                CannotPredictReason::InsufficientData
            ))
        );
    }

    /// ADR192-T5: 学習表が採用されているとき、判定は内蔵表でなく学習表に従う。
    ///
    /// `dependent=false`は変換キーが常にON（セット系＝状態非依存）、`true`は状態によって
    /// トグル/セットが混在する（開閉依存）セル集合。
    fn learned_henkan(dependent: bool) -> Vec<Cell> {
        use super::super::key_effect_predictor::{Conv, Stage};
        let mut cells = vec![
            cell(
                false,
                None,
                Stage::None,
                TableKey::Henkan,
                true,
                Some(Conv::C19),
                Disp::None,
            ),
            cell(
                true,
                Some(Conv::C10),
                Stage::None,
                TableKey::Henkan,
                true,
                Some(Conv::C10),
                Disp::None,
            ),
        ];
        if dependent {
            cells.push(cell(
                true,
                Some(Conv::C19),
                Stage::None,
                TableKey::Henkan,
                false,
                Some(Conv::C19),
                Disp::None,
            ));
        }
        cells
    }

    #[test]
    fn adr192_t5_learned_table_overrides_bundled_classification() {
        let keymap = KeyEffectKeymap::from_config(Some(1), None, &[]).unwrap();
        // 内蔵表(ATOK)では変換キーは開閉依存（既存テスト`adr192_open_axis_verification_table`）。
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, None),
            Some(Classification::StateDependent(StateDependentAxis::Open))
        );
        // 学習表が「常にON」（冪等）と示していれば、警告は出さない側に揃う。
        let idempotent = learned_henkan(false);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, Some(&idempotent)),
            Some(Classification::StateIndependent)
        );
        // 学習表が開閉依存と示していれば、状態依存。
        let dependent = learned_henkan(true);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, Some(&dependent)),
            Some(Classification::StateDependent(StateDependentAxis::Open))
        );
    }

    #[test]
    fn adr192_t5_learned_table_without_the_key_falls_back_to_bundled() {
        use super::super::key_effect_predictor::Stage;
        let keymap = KeyEffectKeymap::from_config(Some(1), None, &[]).unwrap();
        // 学習表に無変換(0x1D)のセルしか無ければ、変換(0x1C)は従来の内蔵表判定のまま。
        let only_muhenkan = [cell(
            false,
            None,
            Stage::None,
            TableKey::Muhenkan,
            true,
            None,
            Disp::None,
        )];
        assert_eq!(
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, Some(&only_muhenkan)),
            classify_state_dependent_mode_key(Some(&keymap), 0x1C, None)
        );
    }

    #[test]
    fn adr192_t5_learned_table_classifies_presets_that_have_no_bundled_table() {
        // Microsoft IME本体は同梱表が無く常に`InsufficientData`だが、学習表があれば判定できる。
        let native = KeyEffectKeymap::for_msime_native(false, None, None, None);
        let idempotent = learned_henkan(false);
        assert_eq!(
            classify_state_dependent_mode_key(Some(&native), 0x1C, Some(&idempotent)),
            Some(Classification::StateIndependent)
        );
        // keymap自体が不明なら学習表があっても判定しない（何のIMEの表か分からない）。
        assert_eq!(
            classify_state_dependent_mode_key(None, 0x1C, Some(&idempotent)),
            Some(Classification::CannotPredict(
                CannotPredictReason::AmbiguousKeymap
            ))
        );
    }
}
